package uz.zero.mmapp

enum class ErrorCode(val code: Int) {
    USER_NOT_FOUND(404),
    USER_ALREADY_EXISTS(409),
    ORGANIZATION_NOT_FOUND(404),
    ORGANIZATION_ALREADY_EXISTS(409),
    EMPLOYEE_NOT_FOUND(404),
    EMPLOYEE_ALREADY_EXISTS(409),
    INVALID_REQUEST(400),
    UNAUTHORIZED(401),
    FORBIDDEN(403),
    INACTIVE_USER(400),
    INACTIVE_ORGANIZATION(400),
    CATEGORY_NOT_FOUND(404),
    BAD_CREDENTIALS(401),
    OLD_PASSWORD_INCORRECT(400),
    FUTURE_DATE_NOT_ALLOWED(400),
    VALIDATION_ERROR(400)
}

enum class UserRole {
    ROLE_USER, ROLE_ADMIN
}